spring.application.name=errorcodebackend
spring.mongodb.uri=mongodb+srv://group12thesiserrorcode_db_user:hR9i8Grf21lbPxio@errorcode.ougjyrp.mongodb.net/Error_Codes?retryWrites=true&w=majority
server.address=0.0.0.0
server.port=8080

# bind to all interfaces for testing on local network
# Spring Boot connects to MongoDB URI for access and exposes Atlas data through endpoints, which would be used by Android
# TODO: replace local test port and deploy behind HTTPS/reverse proxy in production